package com.hieu.edurepo.enums;

public enum NotificationType {
    ADMIN_MESSAGE,
    DOCUMENT_SUBMITTED,
    DOCUMENT_UNDER_REVIEW,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_REVISION_REQUIRED,
    DOCUMENT_PUBLISHED
}
