ALTER TABLE users ADD COLUMN phone_number VARCHAR(30);
ALTER TABLE users ADD COLUMN affiliation VARCHAR(150);
ALTER TABLE users ADD COLUMN bio VARCHAR(1000);
ALTER TABLE users ADD COLUMN avatar_key VARCHAR(255);
ALTER TABLE users ADD COLUMN deleted_at DATETIME(6);
ALTER TABLE users ADD COLUMN bootstrap_key VARCHAR(64);
